### ISSUE TITLE
bundle install

### ISSUE THREAD

**Issue by taicharan** [ysk1180/bigtutorial#1]
gemfileをページの通り編集してbundle installしたところ

An error occurred while installing ovirt-engine-sdk (4.2.4),
and Bundler cannot continue.
Make sure that `gem install ovirt-engine-sdk -v '4.2.4'` succeeds
before bundling.

In Gemfile:
  fog was resolved to 2.0.0, which depends on
    fog-ovirt was resolved to 1.0.3, which depends on
      ovirt-engine-sdk

というエラーメッセージが出ました。
解決方法がわかれば教えていただきたいです。
作業環境はCloud9です。

**Comment by ysk1180** [comment]
@taicharan ご質問いただきありがとうございます。
エラーメッセージを拝見すると、
`gem install ovirt-engine-sdk -v '4.2.4'`
を行うように、と書いてあると思うのですがこちらは実行されましたでしょうか。

**Comment by ysk1180** [comment]
こちら1ヶ月以上動きが無い為、一旦クローズさせていただきます。
問題が解決していない場合は再度オープンしていただけますようお願いいたします。
